CREATE TABLE `REMIND` (
`ID`  int(11) NOT NULL ,
`REMIND_TITLE` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,
`REMIND_FRE`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,
`REMIND_TYPE`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,
`REMIND_DATE`  datetime NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP ,
`CREATE_DATE`  datetime NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP ,
`UPDATE_DATE`  datetime NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP ,
`REMIND_COUNT`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,
`IS_DELETE`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,
`PUSH_TYPE`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,
`PUSH_PATH`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,
PRIMARY KEY (`ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
ROW_FORMAT=DYNAMIC
;

ALTER TABLE `REMIND` CHANGE `ID` `ID` INT(11) NOT NULL AUTO_INCREMENT;